import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Naru's Portfolio",
  description: "Generated by create next app",
};

const MainLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex flex-col h-screen bg-gray-200">
          <main className="flex-1 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
};

export default MainLayout;
